name: "Build and publish release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "!v*-*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build with default Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build with postgresql Maven
        run: mvn --batch-mode --update-snapshots package -P db-postgresql
      - name: Build with mariadb Maven
        run: mvn --batch-mode --update-snapshots package -P db-mariadb
      - name: add files to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
          updateOnlyUnreleased: true
          artifacts: "./target/ghs-server-${{github.ref_name}}.jar,./target/ghs-server-${{github.ref_name}}-postgresql.jar,./target/ghs-server-${{github.ref_name}}-mariadb.jar"
      - name: publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          generateReleaseNotes: true
          updateOnlyUnreleased: true
