name: "Build and publish release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "!v*-*"

jobs:
  create_release:
    name: Release JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build with default Maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: Build with postgresql Maven
        run: mvn --batch-mode --update-snapshots clean package -P db-postgresql
      - name: Build with mariadb Maven
        run: mvn --batch-mode --update-snapshots clean package -P db-mariadb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/ghs-server-${{github.ref_name}}.jar
            ./target/ghs-server-${{github.ref_name}}-postgresql.jar
            ./target/ghs-server-${{github.ref_name}}-mariadb.jar
